apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: centos-vm
  namespace: kubevirt
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: centos-vm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
        resources:
          requests:
            memory: 1Gi
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/centos:8.4
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: centos
              chpasswd: { expire: False }
              ssh_pwauth: true
              disable_root: false