apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win2022-disk-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi   # Adjust size as needed for your Windows VM
  volumeName: win2022-disk