# windows-unattend-iso-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-unattend-iso-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi # or the size of your unattend ISO
  volumeName: windows-unattend-iso