# windows-installer-iso-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-installer-iso-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi # or the size of your ISO
  volumeName: windows-installer-iso